# Generated by Django 3.0.7 on 2020-06-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200615_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='phone',
            field=models.IntegerField(max_length=30, null=True),
        ),
    ]
