# Generated by Django 3.0.7 on 2020-06-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200615_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='user_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Hospital', 'Hospital')], max_length=200, null=True),
        ),
    ]
