# Generated by Django 3.0.7 on 2020-06-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200615_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
