# Generated by Django 3.0.7 on 2020-06-15 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200615_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('fee_per_day', models.IntegerField(null=True)),
                ('experience', models.CharField(choices=[('1 year', '1 year'), ('2 years', '2 years'), ('3+ years', '3+ years')], max_length=30, null=True)),
                ('wworking_days', models.CharField(choices=[('Sunday Monday Tuesday', 'Sunday Monday Tuesday'), ('Monday Tuesday Wednesday', 'Monday Tuesday Wednesday'), ('Tuesday Wednesday Thrusday', 'Tuesday Wednesday Thrusday'), ('Friday Saturday Sunday', 'Friday Saturday Sunday')], max_length=30, null=True)),
                ('qualification', models.CharField(max_length=30, null=True)),
                ('systemuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.SystemUser')),
            ],
        ),
    ]
