# Generated by Django 3.0.7 on 2020-06-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30, null=True),
        ),
    ]
