# Generated by Django 3.0.7 on 2020-06-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200615_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='wworking_days',
        ),
        migrations.AddField(
            model_name='nurse',
            name='working_days',
            field=models.CharField(choices=[('Sunday, Monday, Tuesday', 'Sunday, Monday, Tuesday'), ('Monday, Tuesday, Wednesday', 'Monday, Tuesday, Wednesday'), ('Tuesday, Wednesday, Thrusday', 'Tuesday, Wednesday, Thrusday'), ('Friday, Saturday, Sunday', 'Friday, Saturday, Sunday')], max_length=30, null=True),
        ),
    ]
