# Generated by Django 3.0.7 on 2020-06-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200615_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='qualification',
            field=models.CharField(choices=[('B.Sc in Nursing', 'B.Sc in Nursing'), ('Diploma in Nursing', 'Diploma in Nursing')], max_length=30, null=True),
        ),
    ]
