# Generated by Django 3.0.7 on 2020-06-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
