# Generated by Django 3.0.7 on 2020-06-29 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_hire_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hire',
            name='hospital',
        ),
        migrations.AddField(
            model_name='hire',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Nurse'),
        ),
    ]
