# Generated by Django 3.0.7 on 2020-06-29 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20200630_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Hospital'),
        ),
    ]
