# Generated by Django 3.0.7 on 2020-07-02 01:23

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_hire_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='prescribe_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=account.models.Patient),
        ),
    ]
