# Generated by Django 3.0.7 on 2020-07-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20200702_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='prescribe_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
